version: "{build}"

# Uncomment to debug via RDP
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: yn73CHgZq4yvPt+v6fFUvKKA4YPZ5fyQ1JzctBZ9298=
  GOPATH: c:\gopath
  GOVERSION: 1.10.3
  DEPVERSION: v0.4.1
  DOCKER_VERSION: 18.06.0-ce

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - go version
  - go env
  - git clone -q --branch=master https://github.com/docker/cli.git c:\gopath\src\github.com\docker\cli
  - cd c:\gopath\src\github.com\docker\cli
  - git checkout v%DOCKER_VERSION%
  - ps: |
      "package cli
      var (
        PlatformName = """"
        Version      = ""$env:DOCKER_VERSION""
        GitCommit    = ""$(git rev-parse --short HEAD)""
        BuildTime    = ""$(get-date)""
      )" | Out-File -Encoding Ascii "C:\gopath\src\github.com\docker\cli\cli\version.go"

build_script:
  - ps: .\scripts\make.ps1 -Binary
  - copy C:\gopath\src\github.com\docker\cli\build\docker.exe C:\projects\docker-cli-builder\

test_script:
  - cd C:\projects\docker-cli-builder
  - .\docker.exe --version

artifacts:
- path: .\docker.exe
  name: Binary

deploy:
  release: $(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: FA0xahKGq6AVJEOd1Oen0xPbbM3C9qETfDj69A93xeVyLDlQazwyJa1Si6fn8OMo
  artifact: .\docker.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
